version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      python-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
      timezone: "America/Chicago"
