name: Labeler

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    uses: esacteksab/.github/.github/workflows/labeler.yml@848feff4f2e6fa028d7f3dae9193dcc1129a16e5  # v0.87.9
