name: Pre-Commit

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SKIP: ${{ vars.SKIP }}

permissions:
  contents: read

jobs:
  precommit-reusable:
    uses: esacteksab/.github/.github/workflows/pre-commit.yml@848feff4f2e6fa028d7f3dae9193dcc1129a16e5  # v0.87.9
